theme: jekyll-theme-minimal
color-scheme: auto
title: Yifan Yang (杨轶凡)
description: Deep Learning Architect at NVIDIA
logo: profile.jpg
author:
  email:         yifany AT csail.mit.edu
  googlescholar: https://scholar.google.com/citations?user=J-9nKEYAAAAJ
  github:        Yang-YiFan
  linkedin:      yifan-yang-17a708155
markdown: kramdown